# Generated by Django 5.1.7 on 2025-03-27 19:52
from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('users', 'Profile')

    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
